package com.chvs.webserverdemo.http;

import java.util.Arrays;

public enum HttpHeader {
    ACCEPT("Accept"),
    ACCEPT_CH("Accept-CH"),
    ACCEPT_ENCODING("Accept-Encoding"),
    ACCEPT_LANGUAGE("Accept-Language"),
    ACCEPT_PATCH("Accept-Patch"),
    ACCEPT_POST("Accept-Post"),
    ACCEPT_RANGES("Accept-Ranges"),
    ACCESS_CONTROL_ALLOW_CREDENTIALS("Access-Control-Allow-Credentials"),
    ACCESS_CONTROL_ALLOW_HEADERS("Access-Control-Allow-Headers"),
    ACCESS_CONTROL_ALLOW_METHODS("Access-Control-Allow-Methods"),
    ACCESS_CONTROL_ALLOW_ORIGIN("Access-Control-Allow-Origin"),
    ACCESS_CONTROL_EXPOSE_HEADERS("Access-Control-Expose-Headers"),
    ACCESS_CONTROL_MAX_AGE("Access-Control-Max-Age"),
    ACCESS_CONTROL_REQUEST_HEADERS("Access-Control-Request-Headers"),
    ACCESS_CONTROL_REQUEST_METHOD("Access-Control-Request-Method"),
    AGE("Age"),
    ALLOW("Allow"),
    ALT_SVC("Alt-Svc"),
    ALT_USED("Alt-Used"),
    ATTRIBUTION_REPORTING_ELIGIBLE("Attribution-Reporting-Eligible"),
    ATTRIBUTION_REPORTING_REGISTER_SOURCE("Attribution-Reporting-Register-Source"),
    ATTRIBUTION_REPORTING_REGISTER_TRIGGER("Attribution-Reporting-Register-Trigger"),
    AUTHORIZATION("Authorization"),
    CACHE_CONTROL("Cache-Control"),
    CLEAR_SITE_DATA("Clear-Site-Data"),
    CONNECTION("Connection"),
    CONTENT_DIGEST("Content-Digest"),
    CONTENT_DISPOSITION("Content-Disposition"),
    CONTENT_DPR("Content-DPR"),
    CONTENT_ENCODING("Content-Encoding"),
    CONTENT_LANGUAGE("Content-Language"),
    CONTENT_LENGTH("Content-Length"),
    CONTENT_LOCATION("Content-Location"),
    CONTENT_RANGE("Content-Range"),
    CONTENT_SECURITY_POLICY("Content-Security-Policy"),
    CONTENT_SECURITY_POLICY_REPORT_ONLY("Content-Security-Policy-Report-Only"),
    CONTENT_TYPE("Content-Type"),
    COOKIE("Cookie"),
    CRITICAL_CH("Critical-CH"),
    CROSS_ORIGIN_EMBEDDER_POLICY("Cross-Origin-Embedder-Policy"),
    CROSS_ORIGIN_OPENER_POLICY("Cross-Origin-Opener-Policy"),
    CROSS_ORIGIN_RESOURCE_POLICY("Cross-Origin-Resource-Policy"),
    DATE("Date"),
    DEVICE_MEMORY("Device-Memory"),
    DNT("DNT"),
    DOWNLINK("Downlink"),
    DPR("DPR"),
    EARLY_DATA("Early-Data"),
    ECT("ECT"),
    ETAG("ETag"),
    EXPECT("Expect"),
    EXPECT_CT("Expect-CT"),
    EXPIRES("Expires"),
    FEATURE_POLICY("Feature-Policy"),
    FORWARDED("Forwarded"),
    FROM("From"),
    HOST("Host"),
    IF_MATCH("If-Match"),
    IF_MODIFIED_SINCE("If-Modified-Since"),
    IF_NONE_MATCH("If-None-Match"),
    IF_RANGE("If-Range"),
    IF_UNMODIFIED_SINCE("If-Unmodified-Since"),
    INDEX("Index"),
    KEEP_ALIVE("Keep-Alive"),
    LARGE_ALLOCATION("Large-Allocation"),
    LAST_MODIFIED("Last-Modified"),
    LINK("Link"),
    LOCATION("Location"),
    NEL("NEL"),
    ORIGIN("Origin"),
    PERMISSIONS_POLICY("Permissions-Policy"),
    PING_FROM("Ping-From"),
    PING_TO("Ping-To"),
    PRAGMA("Pragma"),
    PREFER("Prefer"),
    PREFERENCE_APPLIED("Preference-Applied"),
    PROXY_AUTHENTICATE("Proxy-Authenticate"),
    PROXY_AUTHORIZATION("Proxy-Authorization"),
    RANGE("Range"),
    REFERER("Referer"),
    REFERRER_POLICY("Referrer-Policy"),
    REPORT_TO("Report-To"),
    RETRY_AFTER("Retry-After"),
    RTD("RTD"),
    SAVE_DATA("Save-Data"),
    SEC_CH_UA("Sec-CH-UA"),
    SEC_CH_UA_ARCH("Sec-CH-UA-Arch"),
    SEC_CH_UA_BITNESS("Sec-CH-UA-Bitness"),
    SEC_CH_UA_FULL_VERSION("Sec-CH-UA-Full-Version"),
    SEC_CH_UA_FULL_VERSION_LIST("Sec-CH-UA-Full-Version-List"),
    SEC_CH_UA_MOBILE("Sec-CH-UA-Mobile"),
    SEC_CH_UA_MODEL("Sec-CH-UA-Model"),
    SEC_CH_UA_PLATFORM("Sec-CH-UA-Platform"),
    SEC_CH_UA_PLATFORM_VERSION("Sec-CH-UA-Platform-Version"),
    SEC_FETCH_DEST("Sec-Fetch-Dest"),
    SEC_FETCH_MODE("Sec-Fetch-Mode"),
    SEC_FETCH_SITE("Sec-Fetch-Site"),
    SEC_FETCH_USER("Sec-Fetch-User"),
    SEC_GPC("Sec-GPC"),
    SERVER("Server"),
    SERVER_TIMING("Server-Timing"),
    SERVICE_WORKER_NAVIGATION_PRELOAD("Service-Worker-Navigation-Preload"),
    SET_COOKIE("Set-Cookie"),
    SOURCEMAP("SourceMap"),
    STRICT_TRANSPORT_SECURITY("Strict-Transport-Security"),
    TE("TE"),
    TIMING_ALLOW_ORIGIN("Timing-Allow-Origin"),
    TK("Tk"),
    TRAILER("Trailer"),
    TRANSFER_ENCODING("Transfer-Encoding"),
    UPGRADE("Upgrade"),
    UPGRADE_INSECURE_REQUESTS("Upgrade-Insecure-Requests"),
    USER_AGENT("User-Agent"),
    VARY("Vary"),
    VIA("Via"),
    VIEWPORT_WIDTH("Viewport-Width"),
    WARNING("Warning"),
    WIDTH("Width"),
    WWW_AUTHENTICATE("WWW-Authenticate"),
    X_CONTENT_TYPE_OPTIONS("X-Content-Type-Options"),
    X_DNS_PREFETCH_CONTROL("X-DNS-Prefetch-Control"),
    X_FORWARDED_FOR("X-Forwarded-For"),
    X_FORWARDED_HOST("X-Forwarded-Host"),
    X_FORWARDED_PROTO("X-Forwarded-Proto"),
    X_FRAME_OPTIONS("X-Frame-Options"),
    X_XSS_PROTECTION("X-XSS-Protection"),
    UNKNOWN("");

    private final String headerName;

    HttpHeader(String headerName) {
        this.headerName = headerName;
    }

    public String getHeaderName() {
        return headerName;
    }

    public static HttpHeader parse(String headerName) {
        return Arrays.stream(values())
                .filter(v -> v.headerName.equals(headerName))
                .findFirst()
                .orElse(UNKNOWN);
    }
}
